application:
  title: Api Gateway Payment
  description: This Api Payment integrates with enviroment Sandbox of API Cielo's eCommerce

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payment
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: trx-payment.exchange
    queue: trx-payment.queue
    routingkey: trx-payment.routingkey